name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Detect project root (handles nested folder case)
      - name: Detect project root
        run: |
          if [ -f requirements.txt ]; then echo "ROOT=." >> $GITHUB_ENV;
          elif [ -f predictive-maintenance-ml/requirements.txt ]; then echo "ROOT=predictive-maintenance-ml" >> $GITHUB_ENV;
          else echo "requirements.txt not found"; exit 1; fi
          echo "Project root is: $ROOT"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "$ROOT/requirements.txt"

      - name: Run tests
        working-directory: ${{ env.ROOT }}
        run: pytest -q
